#pragma bank 255

/* Border frame only — center art in the old map no longer matches MenuTileset. */

#include "Banks/SetAutoBank.h"
#include "MapInfo.h"
#include "TilesInfo.h"

extern const void __bank_MenuTileset;
extern const struct TilesInfo MenuTileset;

/* Tile indices that still match MenuTileset frame art */
#define T_FILL 0x00
#define T_TL   0x49
#define T_TR   0x4A
#define T_BR   0x4B
#define T_BL   0x4C
#define T_R    0x4D
#define T_B    0x4E
#define T_T    0x4F
#define T_L    0x50

unsigned char GameOvermap_info[] =
{
  T_TL,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_T,T_TR,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_L,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_FILL,T_R,
  T_BL,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_B,T_BR
};

struct MapInfo GameOvermap = {
    .data = GameOvermap_info,
    .width = 20,
    .height = 18,
    .attributes = 0,
    .tiles_bank = (unsigned char)&__bank_MenuTileset,
    .tiles = &MenuTileset
};
